import os
import time

print("İndirme Başlatılıyor...")
time.sleep(3)
os.system("apt-get install python3-pip")
os.system("pip3 install phonenumbers")
os.system("pip3 install colorama")
os.system("apt-get update")
os.system("apt-get install figlet")
os.system("pip3 install pytube")
os.system("pip3 install whois")
os.system("pip3 install onetimepad")
os.system("pip3 install psutil")
os.system("pip3 install tabulate")
os.system("pip3 install speedtest-cli")
os.system("pip3 install instaloader")
os.system("pip3 install tkinter")
os.system("pip3 install wikipedia")
os.system("pip3 install psutil")
os.system("pip3 install speedtest")
os.system("pip3 install tabulate")
os.system("pip3 install wmi")
os.system("pip3 install selenium")
os.system("pip3 install requests")
os.system("pip3 install instagram_explore")
os.system("pip3 install json")
os.system("apt-get install dmitry")
os.system("apt-get install dig")
os.system("apt-get install dnsmap")
os.system("pip3 install bs4")
os.system("pip3 install folium")
os.system("pip3 install webbrowser")
os.system("apt-get install weevely")
os.system("apt-get install dirb")
os.system("apt-get install theHarvester")
os.system("apt-get install skipfish")
os.system("apt-get install figlet")
os.system("apt-get install netdiscover")
os.system("apt install sqlmap")
os.system("apt install nikto")
os.system("apt-get install chkrootkit")
os.system("apt install nmap")
os.system("clear")
print("İndirme Tamamlandı Project-Wings'i Açabilirsiniz...")
