import os
import time
print("İndirme Başlatılıyor...")
time.sleep(3)
os.system("apt-get install python3-pip")
os.system("pip install phonenumbers")
os.system("pip install colorama")
os.system("apt-get update")
os.system("pip install wikipedia")
os.system("pip install selenium")
os.system("pip install requests")
os.system("pip install instagram_explore")
os.system("pip install json")
os.system("apt-get install dmitry")
os.system("apt-get install dig")
os.system("apt-get install dnsmap")
os.system("pip install bs4")
os.system("apt-get install weevely")
os.system("apt-get install dirb")
os.system("apt-get install theHarvester")
os.system("apt-get install skipfish")
os.system("apt-get install figlet")
os.system("apt-get install netdiscover")
os.system("apt install sqlmap")
os.system("apt install nikto")
os.system("apt-get install chkrootkit")
os.system("apt install nmap")
os.system("clear")
print("İndirme Tamamlandı Project-Wings'i Açabilirsiniz...")