import os
import time
print("İndirme Başlatılıyor...")
time.sleep(3)
os.system("apt-get install python3-pip")
os.system("pip install phonenumbers")
os.system("apt-get update")
os.system("apt-get install weevely")
os.system("apt-get install skipfish")
os.system("apt-get install figlet")
os.system("apt-get install netdiscover")
os.system("apt install sqlmap")
os.system("apt install nikto")
os.system("apt-get install chkrootkit")
os.system("apt install nmap")
os.system("clear")
print("İndirme Tamamlandı Project-Wings'i Açabilirsiniz...")